args <- commandArgs(trailingOnly = TRUE)
source("R/read_facility_exchange_config.R")
source("R/hysplit_single_run_smoke.R")
source("R/write_completed_run_index.R")
source("R/run_hysplit_manifest_row.R")
source("R/standardize_hysplit_run_result.R")
source("R/parse_hysplit_run_output.R")
source("R/extract_facility_receptors_from_plume.R")
source("R/validate_hysplit_model_result.R")
source("R/extract_hysplit_dispersion_table.R")
source("R/standardize_hysplit_dispersion_table.R")
source("R/add_tracer_decay_to_dispersion.R")
source("R/apply_tracer_decay.R")
source("R/filter_dispersion_distance.R")
source("R/build_plume_raster_template.R")
source("R/rasterize_hysplit_hourly.R")
source("R/summarize_hysplit_plume.R")
source("R/write_hysplit_parsed_outputs.R")
source("R/prepare_receptor_facilities.R")
source("R/sample_hourly_plume_at_receptors.R")
source("R/summarize_receptor_time_series.R")
source("R/classify_receptor_intercepts.R")
source("R/build_source_receptor_exchange.R")
source("R/write_facility_receptor_outputs.R")
tryCatch({
  cli <- smoke_parse_args(args, require_authorization = TRUE)
  if (!identical(Sys.getenv("EPIPLUME_ALLOW_HYSPLIT_EXECUTION", "false"), "true")) stop("EPIPLUME_ALLOW_HYSPLIT_EXECUTION=true is required.")
  if (!identical(Sys.getenv("EPIPLUME_RUN_IDS", ""), cli$run_id)) stop("EPIPLUME_RUN_IDS must exactly equal the selected run ID.")
  cfg <- read_facility_exchange_config(cli$config); inputs <- smoke_load_manifest(cfg); row <- smoke_select_row(inputs$manifest, cli$run_id); check <- smoke_preflight(cfg, row, allow_overwrite = cli$overwrite, allow_meteorology_download = FALSE)
  smoke_print_spec(check); cat("meteorology acquisition during model execution: not requested\n"); started <- Sys.time()
  metadata <- run_hysplit_manifest_row(row, cfg, dry_run = FALSE, overwrite = cli$overwrite)
  if (!identical(metadata$status, "completed")) stop("HYSPLIT execution failed: ", metadata$error_message)
  parsed <- parse_hysplit_run_output(metadata, cfg, write_outputs = TRUE, overwrite = cli$overwrite)
  extracted <- extract_facility_receptors_from_plume(parsed, inputs$facilities, cfg, write_outputs = TRUE, overwrite = cli$overwrite)
  finished <- Sys.time(); cat("final_status: completed\nelapsed_runtime_seconds:", as.numeric(difftime(finished, started, units = "secs")), "\nproduced_files:\n", paste(c(metadata$actual_output_files, parsed$parsing_metadata$written_files$path, extracted$extraction_metadata$written_files$path), collapse = "\n"), "\n", sep = "")
}, error = function(e) { message("SMOKE RUN FAILED: ", conditionMessage(e)); quit(save = "no", status = 1L) })
