args <- commandArgs(trailingOnly = TRUE)
value <- function(flag, default = NULL) { i <- match(flag, args); if (is.na(i)) default else if (i == length(args)) stop("Missing value for ", flag, call. = FALSE) else args[i + 1L] }
config <- value("--config", "config/facility_exchange_demo.yml"); manifest_path <- value("--manifest")
run_ids <- value("--run-ids"); if (is.null(manifest_path) || is.null(run_ids) || !"--authorize-execution" %in% args) stop("--manifest, --run-ids, and --authorize-execution are required.", call. = FALSE)
if (!identical(Sys.getenv("EPIPLUME_ALLOW_HYSPLIT_EXECUTION", "false"), "true")) stop("EPIPLUME_ALLOW_HYSPLIT_EXECUTION=true is required.", call. = FALSE)
source("R/read_facility_exchange_config.R"); cfg <- read_facility_exchange_config(config); source("R/build_pipeline_run_selection.R")
manifest <- utils::read.csv(manifest_path, stringsAsFactors = FALSE); selected <- build_pipeline_run_selection(manifest, run_ids)
if (nrow(selected) < 2L || nrow(selected) > 6L) stop("Select between 2 and 6 runs.", call. = FALSE)
source("R/validate_hysplit_manifest_row.R"); source("R/prepare_hysplit_meteorology.R"); source("R/plan_hysplit_manifest_meteorology.R"); source("R/validate_manifest_meteorology_plan.R"); source("R/write_manifest_meteorology_outputs.R"); source("R/prepare_hysplit_manifest_meteorology.R"); source("R/assert_manifest_meteorology_ready.R")
source("R/resolve_hysplit_installation.R"); source("R/resolve_hysplit_meteorology.R"); source("R/build_hysplit_run_spec.R"); source("R/run_plume_model.R"); source("R/standardize_hysplit_run_result.R"); source("R/validate_hysplit_model_result.R"); source("R/write_completed_run_index.R"); source("R/run_hysplit_manifest_row.R")
source("R/parse_hysplit_run_output.R"); source("R/write_hysplit_parsed_outputs.R"); source("R/validate_facilities.R"); source("R/simulate_facility_network.R"); source("R/extract_facility_receptors_from_plume.R"); source("R/build_source_receptor_exchange.R"); source("R/write_facility_receptor_outputs.R"); source("R/prepare_receptor_facilities.R"); source("R/sample_hourly_plume_at_receptors.R"); source("R/summarize_receptor_time_series.R"); source("R/classify_receptor_intercepts.R"); source("R/apply_tracer_decay.R"); source("R/filter_dispersion_distance.R"); source("R/standardize_hysplit_dispersion_table.R"); source("R/extract_hysplit_dispersion_table.R"); source("R/add_tracer_decay_to_dispersion.R"); source("R/build_plume_raster_template.R"); source("R/rasterize_hysplit_hourly.R"); source("R/summarize_hysplit_plume.R")
source("R/write_controlled_multirun_ledger.R")
ready <- prepare_hysplit_manifest_meteorology(selected, cfg, allow_download = FALSE, verify = isTRUE(cfg$hysplit$verify_meteorology_after_download)); assert_manifest_meteorology_ready(ready)
if (nrow(ready$plan$unique_files) != 1L || !identical(ready$plan$unique_files$required_filename, "RP202005.gbl")) stop("The smoke selection must use one shared RP202005.gbl file.", call. = FALSE)
reuse_completed <- "--reuse-completed" %in% args
nonempty <- vapply(selected$run_directory, function(x) dir.exists(x) && length(list.files(x, all.files = TRUE, no.. = TRUE)), logical(1))
if (anyDuplicated(selected$run_directory) || any(nonempty & !reuse_completed)) stop("Output directories must be isolated and empty; use --reuse-completed only to reuse completed metadata.", call. = FALSE)
cat("selected run plan:\n"); print(selected[, c("run_id", "source_id", "release_start", "run_directory")], row.names = FALSE)
cat("selected runs:", nrow(selected), " unique sources:", length(unique(selected$source_id)), " unique release times:", length(unique(selected$release_start)), " shared files:", paste(ready$plan$unique_files$required_filename, collapse = ","), "\n", sep = "")
ledger_dir <- file.path(cfg$outputs$root_directory, "controlled_multirun"); ledger <- data.frame(run_id = selected$run_id, source_id = selected$source_id, release_start = selected$release_start, execution_status = "pending", started_at = as.POSIXct(NA), finished_at = as.POSIXct(NA), elapsed_seconds = NA_real_, meteorology_ready = TRUE, meteorology_files = paste(ready$plan$unique_files$required_filename, collapse = ";"), metadata_path = NA_character_, parsed_output_path = NA_character_, receptor_output_path = NA_character_, error_message = NA_character_, warning_count = 0L, stringsAsFactors = FALSE)
write_controlled_multirun_ledger(ledger, ledger_dir)
facilities <- read.csv(file.path(cfg$outputs$root_directory, "data", "facilities.csv"), stringsAsFactors = FALSE)
for (i in seq_len(nrow(selected))) {
  started <- Sys.time(); ledger$execution_status[i] <- "running"; ledger$started_at[i] <- started; write_controlled_multirun_ledger(ledger, ledger_dir)
  outcome <- tryCatch({ existing_metadata <- file.path(selected$run_directory[i], "run_metadata.rds"); metadata <- if (reuse_completed && file.exists(existing_metadata)) readRDS(existing_metadata) else run_hysplit_manifest_row(selected[i, , drop = FALSE], cfg, dry_run = FALSE, overwrite = FALSE); if (!identical(metadata$status, "completed")) stop(metadata$error_message %||% "HYSPLIT execution failed.", call. = FALSE); parsed <- parse_hysplit_run_output(metadata, cfg, write_outputs = TRUE, overwrite = reuse_completed); extracted <- extract_facility_receptors_from_plume(parsed, facilities, cfg, write_outputs = TRUE, overwrite = reuse_completed); list(status = "completed", metadata_path = existing_metadata, parsed_output_path = file.path(selected$run_directory[i], "parsed", "parsed_plume.rds"), receptor_output_path = file.path(selected$run_directory[i], "receptors", "source_receptor_exchange.csv"), warning_count = length(metadata$warnings), error_message = NA_character_) }, error = function(e) list(status = "failed", metadata_path = NA_character_, parsed_output_path = NA_character_, receptor_output_path = NA_character_, warning_count = 0L, error_message = conditionMessage(e)))
  ledger$execution_status[i] <- outcome$status; ledger$metadata_path[i] <- outcome$metadata_path; ledger$parsed_output_path[i] <- outcome$parsed_output_path; ledger$receptor_output_path[i] <- outcome$receptor_output_path; ledger$warning_count[i] <- outcome$warning_count; ledger$error_message[i] <- outcome$error_message
  finished <- Sys.time(); ledger$finished_at[i] <- finished; ledger$elapsed_seconds[i] <- as.numeric(difftime(finished, started, units = "secs")); write_controlled_multirun_ledger(ledger, ledger_dir); cat(ledger$run_id[i], ": ", ledger$execution_status[i], if (!is.na(ledger$error_message[i]) && nzchar(ledger$error_message[i])) paste0(" — ", ledger$error_message[i]) else "", "\n", sep = "")
}
if (any(ledger$execution_status == "failed")) quit(save = "no", status = 1L)
