args <- commandArgs(trailingOnly = TRUE)
value <- function(flag, default = NULL) { i <- match(flag, args); if (is.na(i)) default else if (i == length(args)) stop("Missing value after ", flag, call. = FALSE) else args[i + 1L] }
exclusive <- function(yes, no) if (yes %in% args && no %in% args) stop("Options are mutually exclusive: ", yes, " and ", no, call. = FALSE)
exclusive("--continue-on-error", "--stop-on-error"); exclusive("--reuse-completed", "--no-reuse-completed"); exclusive("--parse", "--no-parse"); exclusive("--extract-receptors", "--no-extract-receptors")
known_flags <- c("--authorize-execution", "--authorize-full-manifest", "--continue-on-error", "--stop-on-error", "--retry-failed", "--reuse-completed", "--no-reuse-completed", "--parse", "--no-parse", "--extract-receptors", "--no-extract-receptors")
known_values <- c("--config", "--manifest", "--run-ids", "--workers")
i <- 1L; while (i <= length(args)) { if (args[i] %in% known_flags) i <- i + 1L else if (args[i] %in% known_values) i <- i + 2L else stop("Unknown option: ", args[i], call. = FALSE) }
if (!"--authorize-execution" %in% args || !identical(tolower(Sys.getenv("EPIPLUME_ALLOW_HYSPLIT_EXECUTION")), "true")) stop("Execution requires --authorize-execution and EPIPLUME_ALLOW_HYSPLIT_EXECUTION=true.", call. = FALSE)
config <- value("--config"); manifest_path <- value("--manifest"); ids <- value("--run-ids")
if (is.null(config) || is.null(manifest_path)) stop("--config and --manifest are required.", call. = FALSE)
if (is.null(ids) && !"--authorize-full-manifest" %in% args) stop("Omitting --run-ids requires --authorize-full-manifest.", call. = FALSE)
invisible(lapply(sort(list.files("R", pattern = "\\.R$", full.names = TRUE)), source))
cfg <- read_facility_exchange_config(config); manifest <- utils::read.csv(manifest_path, stringsAsFactors = FALSE)
selected <- if (is.null(ids)) manifest else build_pipeline_run_selection(manifest, ids)
states <- classify_manifest_execution_state(selected, cfg); print(as.data.frame(table(states$execution_state), stringsAsFactors = FALSE))
cat("eligible:", sum(states$eligible_for_execution | states$eligible_for_postprocessing), " skipped:", sum(states$execution_state == "completed"), " blocked:", sum(states$execution_state %in% c("meteorology_blocked", "running", "invalid")), " failed:", sum(grepl("failed$", states$execution_state)), "\n")
result <- tryCatch(run_hysplit_manifest_subset(manifest, cfg, run_ids = ids, workers = as.integer(value("--workers", 1L)), continue_on_error = !"--stop-on-error" %in% args, retry_failed = "--retry-failed" %in% args, reuse_completed = !"--no-reuse-completed" %in% args, parse_outputs = !"--no-parse" %in% args, extract_receptors = !"--no-extract-receptors" %in% args), error = function(e) { message("ERROR: ", conditionMessage(e)); quit(save = "no", status = 1L) })
print(result$state_summary); if (any(grepl("failed|blocked|invalid|running", names(result$state_summary)))) quit(save = "no", status = 1L)
