#' Write reproducible multi-run connectivity products
write_multirun_connectivity_outputs <- function(assembled, output_directory, overwrite = FALSE) {
  directory <- file.path(output_directory, "multirun"); if (dir.exists(directory) && length(list.files(directory, all.files = TRUE, no.. = TRUE)) && !isTRUE(overwrite)) stop("Multi-run output directory is not empty; use `overwrite = TRUE`: ", directory, call. = FALSE); dir.create(directory, recursive = TRUE, showWarnings = FALSE)
  atomic <- function(path, writer) { tmp <- tempfile(paste0(basename(path), "-"), tmpdir = directory); on.exit(unlink(tmp), add = TRUE); writer(tmp); if (file.exists(path)) unlink(path); if (!file.rename(tmp, path)) stop("Could not install output: ", path, call. = FALSE); normalizePath(path, winslash = "/") }
  tables <- list(run_inventory.csv = assembled$run_inventory, run_processing_log.csv = assembled$run_processing_log, combined_source_receptor_exchange.csv = assembled$combined_exchange_table, connectivity_by_release.csv = assembled$time_summaries$release, connectivity_by_day.csv = assembled$time_summaries$day, connectivity_by_week.csv = assembled$time_summaries$week, connectivity_by_month.csv = assembled$time_summaries$month, source_connectivity_summary.csv = assembled$source_summary, receptor_connectivity_summary.csv = assembled$receptor_summary, dyad_connectivity_summary.csv = assembled$dyad_summary)
  written <- vapply(names(tables), function(name) atomic(file.path(directory, name), function(path) utils::write.csv(tables[[name]], path, row.names = FALSE)), character(1))
  matrix_files <- c(intercept_frequency = "connectivity_matrix_intercept_frequency.rds", n_intercept_runs = "connectivity_matrix_n_intercept_runs.rds", total_particle_count_cumulative = "connectivity_matrix_particle_count.rds")
  for (key in intersect(names(matrix_files), names(assembled$connectivity_matrices))) written <- c(written, atomic(file.path(directory, matrix_files[[key]]), function(path) saveRDS(assembled$connectivity_matrices[[key]], path)))
  rds <- normalizePath(file.path(directory, "assembly_metadata.rds"), winslash = "/", mustWork = FALSE); json <- normalizePath(file.path(directory, "assembly_metadata.json"), winslash = "/", mustWork = FALSE)
  metadata <- assembled$assembly_metadata; metadata$package_versions <- list(R = as.character(getRversion()), terra = as.character(utils::packageVersion("terra")), sf = as.character(utils::packageVersion("sf"))); commit <- tryCatch(system2("git", c("rev-parse", "HEAD"), stdout = TRUE, stderr = FALSE), error = function(e) NA_character_); metadata$repository_commit <- if (length(commit) == 1L) commit else NA_character_; metadata$written_files <- data.frame(path = c(written, rds, json), md5 = c(unname(tools::md5sum(written)), NA_character_, NA_character_), stringsAsFactors = FALSE); metadata$self_checksum_note <- "Metadata self-checksums are NA to avoid recursive content."
  atomic(json, function(path) jsonlite::write_json(metadata, path, auto_unbox = TRUE, pretty = TRUE, null = "null", POSIXt = "ISO8601")); atomic(rds, function(path) saveRDS(metadata, path)); metadata
}
