#' Write pipeline status in CSV, RDS, and optional JSON forms
write_pipeline_status_summary <- function(cfg, manifest, inventory, parsing_results, receptor_results, multirun_result, output_path, config_path = Sys.getenv("EPIPLUME_CONFIG", "config/facility_exchange_demo.yml"), started_at = Sys.time()) {
  dir.create(output_path, recursive = TRUE, showWarnings = FALSE)
  normalize_results <- function(x) { if (is.null(x)) list() else if (!is.null(x$status) && !is.null(x$run_id)) list(x) else x }
  parsing_results <- normalize_results(parsing_results); receptor_results <- normalize_results(receptor_results)
  exchange <- multirun_result$combined_exchange_table
  count_status <- function(status) sum(inventory$run_status == status)
  commit <- tryCatch(system2("git", c("rev-parse", "HEAD"), stdout = TRUE, stderr = FALSE), error = function(e) NA_character_)
  summary <- data.frame(scenario_id = cfg$project$scenario_id, configuration_path = normalizePath(config_path, winslash = "/", mustWork = FALSE), configuration_checksum = unname(tools::md5sum(config_path)), repository_commit = if (length(commit) == 1L) commit else NA_character_, pipeline_started_at = as.POSIXct(started_at, tz = "UTC"), pipeline_finished_at = as.POSIXct(Sys.time(), tz = "UTC"), manifest_run_count = nrow(manifest), planned_run_count = count_status("planned"), missing_run_count = count_status("missing"), dry_run_count = count_status("dry_run"), failed_run_count = count_status("failed"), completed_run_count = count_status("completed"), parsed_run_count = sum(inventory$parse_status == "parsed"), receptor_extracted_run_count = sum(inventory$receptor_status == "receptor_extracted"), successful_target_branches = sum(vapply(receptor_results, function(x) identical(x$status, "receptor_extracted"), logical(1))), failed_target_branches = sum(vapply(c(parsing_results, receptor_results), function(x) identical(x$status, "failed"), logical(1))), exchange_row_count = nrow(exchange), intercept_row_count = if (nrow(exchange)) sum(exchange$intercept) else 0, unique_sources = if (nrow(exchange)) length(unique(exchange$source_id)) else 0, unique_receptors = if (nrow(exchange)) length(unique(exchange$receptor_id)) else 0, unique_directed_dyads = if (nrow(exchange)) length(unique(exchange$source_receptor_id)) else 0, targets_store = cfg$pipeline$targets_store, status_directory = output_path, targets_version = as.character(utils::packageVersion("targets")), yaml_version = as.character(utils::packageVersion("yaml")), sf_version = as.character(utils::packageVersion("sf")), terra_version = as.character(utils::packageVersion("terra")), splitr_version = as.character(utils::packageVersion("splitr")), stringsAsFactors = FALSE)
  csv <- file.path(output_path, "pipeline_status.csv"); rds <- file.path(output_path, "pipeline_status.rds"); json <- file.path(output_path, "pipeline_status.json")
  utils::write.csv(summary, csv, row.names = FALSE); saveRDS(summary, rds); if (requireNamespace("jsonlite", quietly = TRUE)) jsonlite::write_json(summary, json, auto_unbox = TRUE, pretty = TRUE, POSIXt = "ISO8601")
  list(summary = summary, files = c(csv, rds, if (file.exists(json)) json else character()))
}
